"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


import os


from pathlib import Path


# Website's name
SITE_NAME = "Updown"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-uh@!)ty@_ol4)fxgr9wtvk(4y*i$_s7chy)cgx1g%!@y(zef7q"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Allowed hosts
ALLOWED_HOSTS = [
    '0.0.0.0',
    '127.0.0.1',
    'localhost',
    '.example.com',
]


# Application definitions
# https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",  # to enable search lookup
    # Third-party
    "crispy_forms",
    "crispy_bootstrap5",
    "debug_toolbar",
    # Local
    "apps.accounts",
    "apps.pages",
    "apps.uploads",
]


SITE_ID = 1


# Warning: The order of MIDDLEWARE is important when using django-debug-toolbar. You
# should include its middleware as early as possible in the list. However, it must come
# after any other middleware that encodes the response’s content, such as GZipMiddleware.
# https://django-debug-toolbar.readthedocs.io/en/latest/index.html
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",  # Django Debug Toolbar
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# https://docs.djangoproject.com/en/dev/ref/settings/#root-urlconf
ROOT_URLCONF = "config.urls"


# https://docs.djangoproject.com/en/dev/ref/settings/#root-urlconf
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = "static/"

# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = (
    BASE_DIR / "apps/accounts/static/",
    BASE_DIR / "apps/pages/static/",
    BASE_DIR / "apps/uploads/static/",
)

# https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = BASE_DIR / 'staticfiles/'


# Media files

# MEDIA_URL is the URL we can use in our templates for the files
MEDIA_URL = '/media/'

# MEDIA_ROOT is the absolute filesystem path to the directory for user-uploaded files
MEDIA_ROOT = BASE_DIR / "media/"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# django-crispy-forms
# https://django-crispy-forms.readthedocs.io/en/latest/install.html#template-packs
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Make django-crispy-forms fail loud
# By default when crispy-forms encounters errors, it fails silently, logs them and
# continues working if possible. Raise exceptions instead of logging, telling you what’s
# going on when you are developing in debug mode.
# https://django-crispy-forms.readthedocs.io/en/2.3/crispy_tag_forms.html#make-crispy-forms-fail-loud
CRISPY_FAIL_SILENTLY = not DEBUG


# custom user model
# https://docs.djangoproject.com/en/dev/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = 'accounts.Account'  # new custom user setting


# Login and Logout redirects
# https://docs.djangoproject.com/en/dev/ref/settings/#login-redirect-url
LOGIN_REDIRECT_URL = 'accounts_home'
LOGOUT_REDIRECT_URL = 'accounts_home'


# The django-debug-toolbar is shown only if your IP address is listed in Django's
# INTERNAL_IPS setting.
# https://docs.djangoproject.com/en/dev/ref/settings/#std-setting-INTERNAL_IPS
# https://django-debug-toolbar.readthedocs.io/en/latest/index.html
INTERNAL_IPS = [
    "127.0.0.1",
    '0.0.0.0',
]

INTERNAL_IPS = [
    "127.0.0.1",
    '0.0.0.0',
]

